# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
    adapter: mysql2
    database: bancheng_test
    host: localhost
    port: 3306
    username: root
    password: "bancheng2013"
    encoding: utf8

production:
    adapter: mysql2
    database: bancheng_production
    host: localhost
    port: 3306
    username: root
    password: "bancheng2013"
    encoding: utf8




