# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: bancheng_development
  port: 3306
  host: bancheng.mysql.rds.aliyuncs.com
  username: bancheng
  password: bancheng2013
  timeout: 5000

test:
    adapter: mysql2
    database: bancheng_test
    host: localhost
    port: 3306
    username: root
    password: "bancheng2013"
    encoding: utf8

production:
  adapter: mysql2
  database: bancheng_production
  port: 3306
  host: bancheng.mysql.rds.aliyuncs.com
  username: bancheng
  password: bancheng2013
  timeout: 5000




