development:
  address: 127.0.0.1
  port: 9312
  config_file: "config/sphinx/development.sphinx.conf"
  bin_path: /usr/local/bin
  ngram_len: 1
  ngram_chars: "U+3000..U+2FA1F"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
test:
  port: 9312
production:
  port: 9312